# Generated by Django 5.2.7 on 2025-10-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_name_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
